# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_test:
    docker:
      - image: circleci/node:16

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd ../Program/Admin/Api |
            npm install --save && npm test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_test:
          filters:
            branches:
              only:
                - main
